services:
  app:
    build:
      context: ./docker
    container_name: employee-app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - employees


  nginx:
    image: nginx:stable
    container_name: e_nginx
    ports:
      - "2020:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - employees

  # frankenphp:
  #   image: dunglas/frankenphp
  #   container_name: frankenphp-app
  #   ports:
  #     - "2020:8080"
  #     - "2021:443"
  #   volumes:
  #     - ./:/app
  #     - ./frankenphp.yaml:/etc/frankenphp.yaml
  #   working_dir: /app
  #   depends_on:
  #     - db
  #   networks:
  #     - employees

  db:
    image: mysql:8
    container_name: e_mysql
    volumes:
      - mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    ports:
      - "3303:3306"
    networks:
      - employees
  
  phpmyadmin:
    container_name: employee-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 6060:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=e_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MAX_EXECUTION_TIME=3600
      - UPLOAD_LIMIT=512M
    networks:
      - employees

  cache:
    container_name: e_cache
    image: redis:alpine
    restart: unless-stopped
    volumes:
        - ./redis:/data
    networks:
      - employees

  redis_admin:
    container_name: e_redisadmin
    image: erikdubbelboer/phpredisadmin
    restart: unless-stopped
    ports:
        - 7009:80
    environment:
        - REDIS_1_HOST=e_cache
    networks:
      - employees

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - employees

volumes:
  mysql-data:
  minio-data:


networks:
  employees: